#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE DATABASE "${LEADFORGE_DB}" OWNER "${POSTGRES_USER}";
CREATE DATABASE "${TASKFORGE_DB}" OWNER "${POSTGRES_USER}";
SQL
